Home/urls.py
from django.contrib import admin
from django.urls import path, include

from . import  views


urlpatterns = [
    path('', views.index, name='index'),
    path('cv', views.cv, name='cv'),
    path('test', views.test, name='test'),
    path('weditor', views.weditor, name='weditor'),

]

Resume/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('portfolio/', include('portfolio.urls'))

]

Home/models.py
from django.db import models


# Create your models here.
class Info(models.Model):
    name = models.CharField(max_length=50)
    designation = models.CharField(max_length=50)
    job_title = models.CharField(max_length=50)
    dob = models.DateField('Date of Birth')
    address = models.TextField(max_length=200)
    nationality = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    about = models.TextField(max_length=1000)

    def __str__(self):
        return self.name


class Social(models.Model):
    name = models.CharField(max_length=50)
    link = models.CharField(max_length=100)
    icon = models.CharField(max_length=100, default=None, blank=True, null=True)
    def __str__(self):
        return self.name


class Hobby(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Skill(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Sub_Skill(models.Model):
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default=None, blank=True, null=True)
    proficiency = models.IntegerField()

    def __str__(self):
        return self.name


class Education(models.Model):
    degree = models.CharField(max_length=50)
    institution = models.CharField(max_length=50)
    start = models.IntegerField()
    end = models.IntegerField(default=None, blank=True, null=True)
    pass_year = models.IntegerField(default=None, blank=True, null=True)
    gpa = models.FloatField()
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.degree

    class Meta:
        ordering = ['-end']

class Training(models.Model):
    name = models.CharField(max_length=100)
    institution = models.CharField(max_length=100)
    start = models.IntegerField()
    end = models.IntegerField(default=None, blank=True, null=True)
    pass_year = models.IntegerField(default=None, blank=True, null=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name


class Training_Topic(models.Model):
    training = models.ForeignKey(Training, on_delete=models.CASCADE)
    topic = models.CharField(max_length=100)

    def __str__(self):
        return self.topic


class Work(models.Model):
    role = models.CharField(max_length=100)
    institution  = models.CharField(max_length=100)
    start = models.IntegerField()
    end = models.IntegerField(default=None, blank=True, null=True)
    contract_year = models.IntegerField(default=None, blank=True, null=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.institution


class Project_Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=200)
    category = models.ForeignKey(Project_Category, on_delete=models.CASCADE)
    image = models.CharField(max_length=200)
    icon = models.CharField(max_length=100, default=None, blank=True, null=True)
    language_and_framework = models.CharField(max_length=200, default=None, blank=True, null=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name



class Project_Feature(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    feature = models.CharField(max_length=100)

    def __str__(self):
        return self.feature


class Project_Tag(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag


class Fact(models.Model):
    name = models.CharField(max_length=100)
    details = models.CharField(max_length=100, default='')
    icon = models.CharField(max_length=100, default='')
    quantity = models.IntegerField()

    def __str__(self):
        return self.name+": "+str(self.quantity)

    class Meta:
        ordering = ['name']
class Testimonial(models.Model):
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=200)
    designation = models.CharField(max_length=100)
    message = models.CharField(max_length=100)

    def __str__(self):
        return self.name+ ": "+self.message

Home/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.template import Context
from django.template.loader import get_template
from django.views.generic.base import View

from .models import *

# Create your views here.
def test(request):
    ar = ['a', 'b', 'c', 'D', 'e']
    context = {
        "ar" : ar
    }
    return render(request, "test.html", context)


def index(request):
    info = Info.objects.all()[:1].get()
    socials = Social.objects.all()
    hobbies = Hobby.objects.all()
    skills = Skill.objects.all()
    educations = Education.objects.all()
    trainings = Training.objects.all()
    works = Work.objects.all()
    testimonials = Testimonial.objects.all()
    facts = Fact.objects.all()
    projects = Project.objects.all()
    context = {
        "info" : info,
        "socials" : socials,
        "hobbies" : hobbies,
        "skills" : skills,
        "educations" : educations,
        "trainings" : trainings,
        "works" : works,
        "testimonials" : testimonials,
        "facts": facts,
        "projects" : projects
    }
    return render(request, "index.html", context)


def cv(request):
    info = Info.objects.all()[:1].get()
    socials = Social.objects.all()
    hobbies = Hobby.objects.all()
    skills = Skill.objects.all()
    educations = Education.objects.all()
    trainings = Training.objects.all()
    works = Work.objects.all()
    testimonials = Testimonial.objects.all()
    facts = Fact.objects.all()
    projects = Project.objects.all()
    context = {
        "info": info,
        "socials": socials,
        "hobbies": hobbies,
        "skills": skills,
        "educations": educations,
        "trainings": trainings,
        "works": works,
        "testimonials": testimonials,
        "facts": facts,
        "projects": projects,
    }
    return render(request, "cv.html", context)



def weditor(request):
    return render(request, "weditor.html")

Home/templates/cv.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>

    <title>CV</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>

    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" media="all"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/resume.css' %}" media="all"/>

</head>
<body>

<div id="doc2" class="yui-t7">
    <div id="inner">

        <div id="hd">
            <div class="yui-gc">
                <div class="yui-u first">
                    <h1>{{ info.name }}</h1>

                    <h2>{{ info.job_title }}</h2>
                </div>

                <div class="yui-u">
                    <div class="contact-info">
                        {#						<h3><a id="pdf" href="#">Download PDF</a></h3>#}
                        <h3><a href="mailto:{{ info.email }}">{{ info.email }}</a></h3>
                        <h3>{{ info.phone }}</h3>
                    </div><!--// .contact-info -->
                </div>
            </div><!--// .yui-gc -->
        </div><!--// hd -->

        <div id="bd">
            <div id="yui-main">
                <div class="yui-b">

                    <div class="yui-gf">
                        <div class="yui-u first">
                            <h2>Profile</h2>
                        </div>
                        <div class="yui-u">
                            <p class="enlarge">
                                {{ info.about }}
                            </p>
                        </div>
                    </div><!--// .yui-gf -->

                    <div class="yui-gf">
                        <div class="yui-u first">
                            <h2>Skills</h2>
                        </div>
                        <div class="yui-u">
                            {% for skill in skills %}
                            <div class="talent">
                                <h2>{{ skill.name }}</h2>
                                <ul class="talent">
                                {% for sub_skill in skill.sub_skill_set.all %}
                                     {{ sub_skill.name }}
                                {% endfor %}
                                </ul>
                            </div>
                            {% endfor %}
                        </div>
                    </div><!--// .yui-gf -->


                    <div class="yui-gf">

                        <div class="yui-u first">
                            <h2>Experience</h2>
                        </div><!--// .yui-u -->

                        <div class="yui-u">
                            {% for work in works %}

                                <div class="job
                                {% if forloop.last %}
                                    last
                                {% endif %}
">
                                    <h2>{{ work.institution }}</h2>
                                    <h3>{{ work.role }}</h3>
                                    <h4>{{ work.start }}-{{ work.end }}</h4>
                                    <p>{{ work.description }}</p>
                                </div>
                            {% endfor %}
                        </div><!--// .yui-u -->
                    </div><!--// .yui-gf -->


                    <div class="yui-gf last">
                        <div class="yui-u first">
                            <h2>Education</h2>
                        </div>
                        <div class="yui-u">

                            {% for education in educations %}
                                <div class="job
                                {% if forloop.last %}
                                    last
                                {% endif %}
">

                                    <h2>{{ education.institution }}</h2>
                                    <h3>{{ education.degree }} &mdash; <strong>{{ education.gpa }} GPA</strong></h3>
                                </div>
                            {% endfor %}
                        </div>

                    </div><!--// .yui-gf -->


                </div><!--// .yui-b -->
            </div><!--// yui-main -->
        </div><!--// bd -->

        <div id="ft">
            <p>{{ info.name }} &mdash; <a href="mailto:{{ info.email }}">{{ info.email }}</a> &mdash;
                {{ info.phone }}</p>
        </div><!--// footer -->

    </div><!-- // inner -->


</div><!--// doc -->


</body>
</html>

Home/templates/invoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django HTMLtoPDF Tutorial</title>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.7.0/build/reset-fonts-grids/reset-fonts-grids.css" media="all"/>
</head>
<body>
    <div id="doc2" class="yui-t7">
    <div id="inner">

        <div id="hd">
            <div class="yui-gc">
                <div class="yui-u first">
                    <h1>{{ info.name }}</h1>

                    <h2>{{ info.job_title }}</h2>
                </div>

                <div class="yui-u">
                    <div class="contact-info">
                        {#						<h3><a id="pdf" href="#">Download PDF</a></h3>#}
                        <h3><a href="mailto:{{ info.email }}">{{ info.email }}</a></h3>
                        <h3>{{ info.phone }}</h3>
                    </div><!--// .contact-info -->
                </div>
            </div><!--// .yui-gc -->
        </div><!--// hd -->

        <div id="bd">
            <div id="yui-main">
                <div class="yui-b">

                    <div class="yui-gf">
                        <div class="yui-u first">
                            <h2>Profile</h2>
                        </div>
                        <div class="yui-u">
                            <p class="enlarge">
                                {{ info.about }}
                            </p>
                        </div>
                    </div><!--// .yui-gf -->

                    <div class="yui-gf">
                        <div class="yui-u first">
                            <h2>Skills</h2>
                        </div>
                        <div class="yui-u">
                            {% for skill in skills %}
                            <div class="talent">
                                <h2>{{ skill.name }}</h2>
                                <ul class="talent">
                                {% for sub_skill in skill.sub_skill_set.all %}
                                     {{ sub_skill.name }}
                                {% endfor %}
                                </ul>
                            </div>
                            {% endfor %}
                        </div>
                    </div><!--// .yui-gf -->


                    <div class="yui-gf">

                        <div class="yui-u first">
                            <h2>Experience</h2>
                        </div><!--// .yui-u -->

                        <div class="yui-u">
                            {% for work in works %}

                                <div class="job
                                {% if forloop.last %}
                                    last
                                {% endif %}
">
                                    <h2>{{ work.institution }}</h2>
                                    <h3>{{ work.role }}</h3>
                                    <h4>{{ work.start }}-{{ work.end }}</h4>
                                    <p>{{ work.description }}</p>
                                </div>
                            {% endfor %}
                        </div><!--// .yui-u -->
                    </div><!--// .yui-gf -->


                    <div class="yui-gf last">
                        <div class="yui-u first">
                            <h2>Education</h2>
                        </div>
                        <div class="yui-u">

                            {% for education in educations %}
                                <div class="job
                                {% if forloop.last %}
                                    last
                                {% endif %}
">

                                    <h2>{{ education.institution }}</h2>
                                    <h3>{{ education.degree }} &mdash; <strong>{{ education.gpa }} GPA</strong></h3>
                                </div>
                            {% endfor %}
                        </div>

                    </div><!--// .yui-gf -->


                </div><!--// .yui-b -->
            </div><!--// yui-main -->
        </div><!--// bd -->

        <div id="ft">
            <p>{{ info.name }} &mdash; <a href="mailto:{{ info.email }}">{{ info.email }}</a> &mdash;
                {{ info.phone }}</p>
        </div><!--// footer -->

    </div><!-- // inner -->


</div><!--// doc -->
</body>
</html>

Home/templates/test.html
Working

Home/templates/weditor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Hello world
</body>
</html>