Home/urls.py
from django.contrib import admin
from django.urls import path, include

from . import  views


urlpatterns = [
    path('', views.index, name='index'),
    path('cv', views.cv, name='cv'),
    path('test', views.test, name='test'),
    path('weditor', views.weditor, name='weditor'),

]

Resume/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('portfolio/', include('portfolio.urls'))

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from . import  views

app_name = 'portfolio'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.test, name='index'),

]

portfolio/models.py
from django.db import models

# Create your models here.

class Project_Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Project_Feature(models.Model):
    feature = models.CharField(max_length=100)

    def __str__(self):
        return self.feature

class Project_Tag(models.Model):
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag

class Project(models.Model):
    name = models.CharField(max_length=100)
    url = models.CharField(max_length=200, default=None, blank=True, null=True)
    category = models.ForeignKey(Project_Category, on_delete=models.CASCADE, default=None, blank=True, null=True)
    image = models.CharField(max_length=200, default=None, blank=True, null=True)
    icon = models.CharField(max_length=100, default=None, blank=True, null=True)
    feature = models.ForeignKey(Project_Feature, on_delete=models.CASCADE, default=None, blank=True, null=True)
    tag = models.ForeignKey(Project_Tag, on_delete=models.CASCADE, default=None, blank=True, null=True)
    description = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name

portfolio/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from portfolio.models import Project, Project_Category


def test(request):
    projects = Project.objects.all()
    tags = Project_Category.objects.all
    context = {
        "projects" : projects,
        "tags" : tags
    }
    return render(request, "portfolio.html", context)
    # return HttpResponse("Hello world")

portfolio/templates/portfolio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from colorlib.com/preview/theme/pixel/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 28 Jan 2019 10:17:26 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8"/><!-- /Added by HTTrack -->
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <title>Pixel - Digital Agency HTML Template</title>

    <link rel="icon" href="{% static 'portfolio/img/core-img/favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'portfolio/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/classy-nav.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/font-awesome.min.css' %}">
</head>
<body>

<div class="preloader d-flex align-items-center justify-content-center">
    <div class="lds-ellipsis">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>

<header class="header-area">

    <div class="pixel-main-menu" id="sticker">
        <div class="classy-nav-container breakpoint-off">
            <div class="container-fluid">

                <nav class="classy-navbar justify-content-between" id="pixelNav">

                    <a href="{% url 'portfolio:index' %}" class="nav-brand"><img src="{% static 'portfolio/img/core-img/logo.png' %}"
                                                                  alt=""></a>

                    <div class="classy-navbar-toggler">
                        <span class="navbarToggler"><span></span><span></span><span></span></span>
                    </div>

                    <div class="classy-menu">

                        <div class="classycloseIcon">
                            <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                        </div>

                        <div class="classynav">
                            <ul>
                                <li><a href="index-2.html">Slideshow</a></li>
                                <li><a href="about.html">Portfolio</a></li>
                                <li><a href="{% url 'index' %}" target="_blank">My Profile</a></li>
                            </ul>

                            <div class="top-social-info ml-5">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>

                    </div>
                </nav>
            </div>
        </div>
    </div>
</header>


<section class="hero-area">
    <div class="hero-slideshow owl-carousel">

        <div class="single-slide">

            <div class="slide-bg-img bg-img"
                 style="background-image: url({% static 'portfolio/img/bg-img/1.jpg' %});"></div>

            <div class="container h-100">
                <div class="row h-100 align-items-center">
                    <div class="col-12 col-lg-9">
                        <div class="welcome-text">
                            <h2 data-animation="fadeInUp" data-delay="300ms"><span>Digital Agency</span><br>of the year
                                2019</h2>
                            <h4 data-animation="fadeInUp" data-delay="500ms">Visual Identity by John Doe Client: <span>Lorem ipsum</span>
                            </h4>
                            <a href="#" class="btn pixel-btn mt-50" data-animation="fadeInUp" data-delay="700ms">View
                                Project</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="single-slide">

            <div class="slide-bg-img bg-img"
                 style="background-image: url({% static 'portfolio/img/bg-img/2.jpg' %});"></div>

            <div class="container h-100">
                <div class="row h-100 align-items-center">
                    <div class="col-12 col-lg-9">
                        <div class="welcome-text">
                            <h2 data-animation="fadeInUp" data-delay="300ms"><span>Creative Agency</span><br>of the year
                                2019</h2>
                            <h4 data-animation="fadeInUp" data-delay="500ms">Visual Identity by John Doe Client: <span>Lorem ipsum</span>
                            </h4>
                            <a href="#" class="btn pixel-btn mt-50" data-animation="fadeInUp" data-delay="700ms">View
                                Project</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="pixel-portfolio-area section-padding-100-0">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="section-heading text-center wow fadeInUp" data-wow-delay="100ms">
                    <h2>Made by pixel</h2>
                    <img src="{% static 'portfolio/img/core-img/x.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>

    <div class="pixel-projects-menu wow fadeInUp" data-wow-delay="200ms">
        <div class="text-center portfolio-menu">
            <button class="btn active" data-filter="*">All Projects</button>
            {% for tag in  tags%}
                <button class="btn" data-filter=".{{ tag.id }}">{{ tag.name }}</button>
            {% endfor %}
{#            <button class="btn" data-filter=".add">Advertising</button>#}
{#            <button class="btn" data-filter=".web">Web Development</button>#}
        </div>
    </div>
    <div class="pixel-portfolio">
        {% for project in projects %}
        <div class="single_gallery_item {{ project.tag_id }} wow fadeInUp" data-wow-delay="0.2s">
            <img src="{% static 'portfolio/img/bg-img/5.jpg' %}" alt="">
            <div class="hover-content text-center d-flex align-items-center justify-content-center">
                <div class="hover-text">
                    <a href="{% static 'portfolio/img/bg-img/5.jpg' %}" class="zoom-img"><i class="fa fa-eye" aria-hidden="true"></i></a>
                    <h4>{{ project.name }}</h4>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>





<footer class="footer-area section-padding-100-0">
    <div class="copywrite-area">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-12 col-md-6">
                    <div class="copywrite-content">

                        <p class="copywrite-text">
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                                                                                aria-hidden="true"></i> by <a
                                href="https://colorlib.com/" target="_blank">Colorlib</a>

                        </p>
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <nav class="footer-nav">
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">Portfolio</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</footer>


<script src="{% static 'portfolio/js/jquery/jquery-2.2.4.min.js' %}"></script>

<script src="{% static 'portfolio/js/bootstrap/popper.min.js' %}"></script>

<script src="{% static 'portfolio/js/bootstrap/bootstrap.min.js' %}"></script>

<script src="{% static 'portfolio/js/plugins/plugins.js' %}"></script>

<script src="{% static 'portfolio/js/active.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
</body>

<!-- Mirrored from colorlib.com/preview/theme/pixel/ by HTTrack Website Copier/3.x [XR&CO'2014], Mon, 28 Jan 2019 10:17:32 GMT -->
</html>

portfolio/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>H</title>
</head>
<body>
    Hello world
</body>
</html>